#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=01:00:00
#PBS -M tlai4@disroot.org
#PBS -m ae
#PBS -j oe

module load cutadapt
module load bowtie2/intel/2.3.2
cd /N/dc2/scratch/timlai/chip2/
cutadapt -f 'fastq' -e 0.05 -m 20 -a \
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCA \
-o GSF2362-Hollenhorst-4-ERG-ACTD_S4_R1_001_clean.fastq \ 
GSF2362-Hollenhorst-4-ERG-ACTD_S4_R1_001.fastq

bowtie2 --no-unal --threads 4 --no-unal --threads 4 -x index/index -U GSF2362-Hollenhorst-4-ERG-ACTD_S4_R1_001_clean.fastq -S S4_clean.sam
