#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=6,walltime=02:00:00
#PBS -M tlai4@disroot.org
#PBS -m ae
#PBS -j oe
cd /N/dc2/scratch/timlai/rna
module load star

STAR --runThreadN 6 --runMode genomeGenerate --genomeFastaFiles hg38.fa --sjdbGTFfile Homo_sapiens.GRCh38.99.chr.gtf --genomeDir indices

files=($(ls *.fastq))
for file in ${files[@]}
do
    STAR --runThreadN 6 --genomeDir indices --readFilesIn $file --outFileNamePrefix STAR/${file}_ --outSAMtype BAM SortedByCoordinate
done

